# Secretları stack içerisinde kullanacaksak versiyon
# en az 3.1 olmalı!
version: "3.1"

services:
    db:
        image: postgres
        secrets:
            - psql_pass
        environment:
            POSTGRES_PASSWORD_FILE=/run/secrets/psql_pass
        
secrets:
    psql_pass:
        file: ./psql_pass.txt
    
    # External secret için:
    # my_external_secret:
        # external: true