# Örnek olarak official nginx imageinin üzerine kendi
# imageimizi oluşturalım. Sadece serverın başlangıç
# sayfasını değiştirelim.

FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY index.html index.html